"use client";

import { useEffect, useRef } from "react";
import styles from "./projects.module.css";
import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

const projects = [
  {
    title: "My Phone AI",
    summary:
      "A smart mobile diagnostic app that instantly checks iPhone authenticity, hardware health, and hidden issues before purchase.",
    tech: "Swift • iOS • CoreData • Device APIs • Cloud Sync • Secure Reporting",
    results: [
      " • Reduced fraud in second-hand phone sales",
      " • Fast device inspection in under 30 seconds",
      " • Trusted by resellers and technicians",
    ],
  },
  {
    title: "My Mac AI",
    summary:
      "A powerful Mac inspection tool designed to analyze hardware status, detect issues, and verify device integrity before resale.",
    tech: "Swift • macOS • System APIs • Hardware Diagnostics • Local Reports",
    results: [
      "	•	Accurate hardware validation",
      "	•	Improved second-hand device confidence",
      "	•	Used by professionals and resellers",
    ],
  },
  {
    title: "My Watch AI",
    summary:
      "An Apple Watch diagnostic solution that checks sensors, performance, and device authenticity with a detailed health report.",
    tech: "Swift • watchOS • iOS Companion App • Bluetooth • Health APIs",
    results: [
      "	•	Reliable smartwatch inspection",
      "	•	Clear health & sensor validation",
      "	•	Optimized for quick on-site testing",
    ],
  },
  {
    title: "Takkad Platform",
    summary:
      "A centralized platform that stores and displays device inspection reports generated by (My Phone Ai, My Mac Ai, My Watch Ai) in one secure place.",
    tech: "Next.js • Node.js • REST APIs • PostgreSQL • Cloud Hosting",
    results: [
      "	•	Unified inspection reports",
      "	•	Easy access for buyers and sellers",
      "	•	Increased transparency in device trading",
    ],
  },
  {
    title: "Onebby",
    summary:
      "A large-scale eCommerce platform for electronics and appliances with advanced filtering, pricing logic, and vendor management.",
    tech: "Next.js • Node.js • PostgreSQL • APIs • Payment Gateways",
    results: [
      "	•	High-performance storefront",
      "	•	Multi-vendor support",
      "	•	Optimized UX for conversions",
    ],
  },
  {
    title: "Dixe Distribuzione",
    summary:
      "A B2B distribution system for electronics, offering inventory control, pricing automation, and partner integrations.",
    tech: "Web Dashboard • APIs • Role-based Access • ERP Logic",
    results: [
      "	•	Streamlined B2B ordering",
      "	•	Automated pricing & stock handling",
      "	•	Improved supplier–client workflow",
    ],
  },
  {
    title: "Tabeby",
    summary:
      "A healthcare platform connecting doctors, clinics, and patients with smart booking and role-based access.",
    tech: "Flutter / Swift • Backend APIs • OTP Auth • Admin Dashboard",
    results: [
      "	•	Faster appointment management",
      "	•	Secure patient–doctor interaction",
      "	•	Scalable medical system architecture",
    ],
  }
];

export default function ProjectContent() {
  const rootRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const root = rootRef.current; // ✅ change to rootRef.current if your ref name is rootRef
    if (!root) return;

    // ---------- helpers ----------
    const q = <T extends Element = HTMLElement>(sel: string) => root.querySelector<T>(sel);
    const qa = <T extends Element = HTMLElement>(sel: string) =>
      Array.from(root.querySelectorAll<T>(sel));

    // ---------- LOADING SCREEN ----------
    const progressBar = q<HTMLElement>("#progress-bar");
    const counter = q<HTMLElement>("#progress-counter");
    const loadingScreen = q<HTMLElement>("#loading-screen");
    const heroSection = q<HTMLElement>(".hero");

    if (!progressBar || !counter || !loadingScreen || !heroSection) return;

    const updateProgress = (p: number) => {
      progressBar.style.width = `${p}%`;
      counter.textContent = `${p}%`;
    };

    updateProgress(0);
    document.body.style.overflow = "hidden";

    let progress = 0;
    const increment = 5;

    // ---------- SITENAME absolute -> relative ----------
    const onScrollSitename = () => {
      const part1 = q<HTMLElement>(".part1");
      const sitename = q<HTMLElement>(".sitename");
      const spacer = q<HTMLElement>(".spacer");
      if (!part1 || !sitename || !spacer) return;

      const part1Top = part1.getBoundingClientRect().top;
      if (part1Top <= 0) {
        sitename.classList.add("relative");
        spacer.classList.add("absolute");
      } else {
        sitename.classList.remove("relative");
        spacer.classList.remove("absolute");
      }
    };

    // ---------- HUGE TEXT fade in ----------
    const isElementInMiddleViewport = (el: HTMLElement) => {
      const rect = el.getBoundingClientRect();
      const elementMiddle = rect.top + rect.height / 2;
      return elementMiddle >= 0 && elementMiddle <= window.innerHeight;
    };

    const onScrollFadeIn = () => {
      const els = qa<HTMLElement>(".fadein");
      els.forEach((el) => {
        if (isElementInMiddleViewport(el)) {
          el.style.opacity = "1";
          el.classList.add("move-up");
        }
      });
    };

    // ---------- ROAD shrinking ----------
    const onScrollRoad = () => {
      const road = q<HTMLElement>(".road");
      if (!road) return;
      const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
      const windowHeight = window.innerHeight;
      const roadHeight = windowHeight - (scrollTop / windowHeight) * windowHeight * 1;
      road.style.height = `${roadHeight}px`;
    };

    // ---------- FIXED CARDS (your same logic) ----------
    const onScrollCards = () => {
      const cards = q<HTMLElement>(".cards");
      const cardTexts = qa<HTMLElement>(".cards-text");
      const images = qa<HTMLElement>(".cards-image");
      const cta = q<HTMLElement>(".cards-cta");
      if (!cards || !cta || images.length === 0 || cardTexts.length === 0) return;

      const windowHeight = window.innerHeight;
      const cardsTop = cards.getBoundingClientRect().top;
      const cardsBottom = cards.getBoundingClientRect().bottom;

      if (cardsTop <= 0 && cardsBottom >= windowHeight) {
        images.forEach((img) => img.classList.add("fixed"));
        cta.classList.add("fixed");
      } else {
        images.forEach((img) => img.classList.remove("fixed"));
        cta.classList.remove("fixed");
      }

      cardTexts.forEach((cardText, index) => {
        const top = cardText.getBoundingClientRect().top;
        if (top <= windowHeight / 2 || index === 0) {
          if (images[index]) {
            images[index].style.opacity = "1";
            images[index].style.display = "flex";
          }
        } else {
          if (images[index]) {
            images[index].style.opacity = "0";
            images[index].style.display = "none";
          }
        }
      });
    };

    // ---------- attach scroll listeners ----------
    window.addEventListener("scroll", onScrollSitename, { passive: true });
    window.addEventListener("scroll", onScrollFadeIn, { passive: true });
    window.addEventListener("scroll", onScrollRoad, { passive: true });
    window.addEventListener("scroll", onScrollCards, { passive: true });

    // initial run
    onScrollSitename();
    onScrollFadeIn();
    onScrollRoad();
    onScrollCards();

    // ---------- GSAP init (Horizontal + Zoom) ----------
    // Keep gsap scoped to this component by using root.querySelector
    const container = q<HTMLElement>(".horizontal-scroller");
    const wrapper = q<HTMLElement>(".horizontal-wrapper");
    const pinContainer = q<HTMLElement>(".horizontal-container");

    let horizontalTween: gsap.core.Tween | null = null;
    let zoomTL: gsap.core.Timeline | null = null;

    const setHorizontalHeight = () => {
      if (!container || !wrapper || !pinContainer) return;

      // how far the horizontal content travels
      const dist = container.scrollWidth - document.documentElement.clientWidth;
      const extra = Math.max(0, dist);

      // ✅ pin container should stay exactly one screen tall
      pinContainer.style.height = `${window.innerHeight}px`;

      // ✅ wrapper holds the “scroll distance” so ScrollTrigger has room
      wrapper.style.height = `${window.innerHeight + extra}px`;
    };

    const initHorizontal = () => {
      if (!container || !wrapper || !pinContainer) return;

      setHorizontalHeight();
      ScrollTrigger.addEventListener("refreshInit", setHorizontalHeight);

      const getWidth = () => container.scrollWidth - document.documentElement.clientWidth;

      horizontalTween = gsap.to(container, {
        x: () => -Math.max(0, getWidth()),
        ease: "none",
        scrollTrigger: {
          trigger: pinContainer,
          start: "top top",
          scrub: 0.5,
          pin: pinContainer,
          end: () => `+=${Math.max(0, getWidth())}`,
          invalidateOnRefresh: true,
          // markers: true,
        },
      });
    };

    const initZoom = () => {
      const zoomEl = q<HTMLElement>(".zoom");
      if (!zoomEl) return;

      zoomTL = gsap.timeline({
        scrollTrigger: {
          trigger: zoomEl,
          scrub: true,
          start: "top top",
          end: "+=1000%",
          pin: true,
          // markers: true,
        },
      });

      zoomTL
        .to(q<HTMLElement>(".zoom-circle"), { scale: 12 }, "sameTime")
        .to(q<HTMLElement>(".zoom-content"), { scale: 1 }, "sameTime");
    };

    // run gsap once loading ends
    const updateLoop = window.setInterval(() => {
      if (progress >= 100) {
        window.clearInterval(updateLoop);

        loadingScreen.style.opacity = "0";
        loadingScreen.style.height = "0";
        heroSection.style.opacity = "1";

        setTimeout(() => {
          document.body.style.overflowY = "auto";
          initHorizontal();
          initZoom();
          ScrollTrigger.refresh(); // ✅ important after heights/pins
        }, 700);

        return;
      }

      updateProgress(progress);
      progress += increment;
    }, 100);

    // ---------- cleanup ----------
    return () => {
      window.clearInterval(updateLoop);
      document.body.style.overflow = "";

      window.removeEventListener("scroll", onScrollSitename);
      window.removeEventListener("scroll", onScrollFadeIn);
      window.removeEventListener("scroll", onScrollRoad);
      window.removeEventListener("scroll", onScrollCards);

      ScrollTrigger.removeEventListener("refreshInit", setHorizontalHeight);

      if (horizontalTween) horizontalTween.kill();
      if (zoomTL) zoomTL.kill();

      // kill any remaining triggers created in this component
      ScrollTrigger.getAll().forEach((t) => t.kill());
    };
  }, []);

  return (
    <div ref={rootRef} className={styles.scope}>
      {/* LOADING SCREEN */}
      <div id="loading-screen">
        <div id="progress-bar"></div>
        <div id="progress-counter">0%</div>
      </div>

      {/* HERO SECTION */}
      <div className="hero">
        <div className="sun">
          <div className="semicircle"></div>
          <div className="line"></div>
        </div>
        <div className="road"></div>
      </div>

      {/* HUGE TEXTS */}
      <div className="part1">
        <p className="sitename">OUR PROJECTS</p>
        <div className="spacer"></div>
        <div className="big-text">
          <p className="fadein">WEBSITES</p>
          <p className="fadein">MOBILE APPS</p>
          <p className="fadein">DESKTOP APPS</p>
        </div>
      </div>

      {/* HORIZONTAL SCROLL */}
      <div className="horizontal-container">
        <div className="horizontal-wrapper">
          <div className="horizontal-scroller">
            <div className="row">
              <div className="item filled">
                <p className="itemTitle">My Phone Ai</p>
                <p>Refers to a specific utility app for checking device health,
                  but more broadly.</p>
                <a className="link item-link">
                  <span className="link-text" data-text="Download">
                    Check on appstore
                  </span>
                </a>
              </div>

              <div className="item filled">
                <p className="itemTitle">My Mac Ai</p>
                <p>Checking your Mac before buying it has become very easy
                  with the Mac Ai app.</p>
                <a className="link item-link">
                  <span className="link-text" data-text="">
                    Private use
                  </span>
                </a>
              </div>

              <div className="item big">
                <p>+4 Years of cooperation</p>
                <p>My phillie wireless for information technology</p>
              </div>

              <div className="item filled">
                <p className="itemTitle">My Watch Ai</p>
                <p>Check the watch before you buy it and get a full and
                  detailed report on all its features and problems.</p>
                <a className="link item-link">
                  <span className="link-text" data-text="">
                    Private use
                  </span>
                </a>
              </div>

              <div className="item filled">
                <p className="itemTitle">Takkad</p>
                <p>A website dedicated to receiving reports from inspected
                  devices (My Phone Ai, My Mac Ai, My Watch Ai); anyone can obtain a detailed report.</p>
                <a className="link item-link">
                  <span className="link-text" data-text="Open link">
                    Direct to website
                  </span>
                </a>
              </div>

              <div className="item">
                <p>From cutting-edge startups to established businesses,
                  we have experience across industries and organization sizes.</p>
              </div>
            </div>

            <div className="row">
              <div className="item big">
                <p>Contact us today and let us help you build that next great software turning disruption into opportunity</p>
              </div>

              <div className="item filled">
                <p className="itemTitle">Onebby.it</p>
                <p>Onebby is among the top 3 stores in Italy for low prices on appliances,
                  telephony and IT of the best brands.</p>
                <a className="link item-link">
                  <span className="link-text" data-text="Open link">
                    Direct to website
                  </span>
                </a>
              </div>

              <div className="item filled">
                <p className="itemTitle">Dixe Distribuzione</p>
                <p>Dixe is the B2B distributor of appliances that follows market trends and listens
                  to the requests of its customers to always offer innovative, advanced and
                  trendy products.</p>
                <a className="link item-link">
                  <span className="link-text" data-text="Open link">
                    Direct to website
                  </span>
                </a>
              </div>

              <div className="item big">
                <p>+2 Years of cooperation</p>
                <p>Website, Dashboard, APIs, Database,
                  iOS and android apps</p>
              </div>

              <div className="item filled">
                <p className="itemTitle">Tabeby</p>
                <p>Doctor/Secretary/Patient ecosystem with booking flows and OTP authentication.</p>
                <a className="link item-link">
                  <span className="link-text" data-text="Download">
                    Check on appstore
                  </span>
                </a>
              </div>

              <div className="item filled">
                <p>and many more...</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* FIXED CARDS */}
      <div className="cards-container">
        <div
          className="cards"
          style={{ ["--cards-count" as any]: projects.length }}
        >
          <div className="cards-text-container">
            {projects.map((p) => (
              <div key={p.title} className="cards-text">
                <h2>{p.title}</h2>

                <p>{p.summary}</p>
                <p>{p.tech}</p>

                <ul className="resultsList">
                  {p.results.map((r) => (
                    <li key={r}>{r}</li>
                  ))}
                </ul>
              </div>
            ))}

            <div className="cards-cta">GET STARTED</div>
          </div>

          <div className="cards-image-container">
            <div className="cards-image">
              <img
                className="image"
                src="/images/myphoneai-img.png"
                alt="My Phone AI"
              />
            </div>

            <div className="cards-image">
              <img
                className="image"
                src="/images/mymacai-img.png"
                alt="My Mac AI"
              />
            </div>

            <div className="cards-image">
              <img
                className="image"
                src="/images/mywatchai-img.png"
                alt="My Watch AI"
              />
            </div>

            <div className="cards-image">
              <img
                className="image"
                src="/images/takkad-img.png"
                alt="Takkad website"
              />
            </div>

            <div className="cards-image">
              <img
                className="image"
                src="/images/onebby-web-img.png"
                alt="Onebby website"
              />
            </div>

            <div className="cards-image">
              <img
                className="image"
                src="/images/dixe-web-img.png"
                alt="Dixe website"
              />
            </div>

            <div className="cards-image">
              <img
                className="image"
                src="/images/tabeby-img.png"
                alt="Tababy app"
              />
            </div>
          </div>
        </div>
      </div>

      {/* ZOOM */}
      <div className="zoom-container">
        <div className="zoom">
          <h2 className="zoom-heading">KEEP SCROLLING TO ZOOM</h2>
          <div className="zoom-circle"></div>
          <h3 className="zoom-content">ZOOM INNN</h3>

          <div className="footer">
            <p className="footer-content">Thanks for watching!</p>
            <a className="footer-content link" href="#">
              <span className="link-text" data-text="Let's connect">
                Let's connect
              </span>
            </a>
          </div>
        </div>
      </div>

      <div style={{ height: "300vh" }} />
    </div>
  );
}